- .github/workflows/deploy.yml
> YEL-9 [setting] 빌드 스크립트 오타 수정

- build.gradle
- docker/docker-compose.blue.yml
- docker/docker-compose.green.yml
- src/main/java/com/yello/server/configuration/RedisConfiguration.java
- src/main/java/com/yello/server/controller/HealthCheckController.java
* resolves 
* Redis 데이터베이스 연결을 위한 docker-compose 파일 수정
*
> YEL-23 [feat] Redis 설정 추가

- scripts/deploy.sh
> YEL-23 [setting] 레디스 설정에 따른 deploy.sh 수정

- docker/docker-compose.blue.yml
- docker/docker-compose.green.yml
> [YEL-23/setting] 레디스 Depend 제거

- docker/docker-compose.blue.yml
- docker/docker-compose.green.yml
> YEL-23 [setting] redis 세팅

- src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/dto/response/KeywordCheckResponse.java
- src/main/java/com/yello/server/domain/vote/entity/Vote.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
- src/main/java/com/yello/server/global/common/ControllerExceptionAdvice.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/test/java/com/yello/server/friend/FriendControllerTest.java
* resolves YEL-30
* 포인트 사용시 keyword 확인하고, isAnswerRevealed = true로 바꾸도록 구현
*
> YEL-30 [Feat] 포인트 사용시 keyword 확인 API 개발

- src/main/java/com/yello/server/domain/vote/dto/response/VoteContentVO.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteResponse.java
> YEL-22 [update] 투표 응답값 변경에 따른 DTO 수정

- README.md
> YEL-30 [update] Update README.md

- src/main/java/com/yello/server/domain/authorization/configuration/SecurityConfiguration.java
- src/main/java/com/yello/server/domain/authorization/configuration/WebMvcConfig.java
- src/main/java/com/yello/server/domain/authorization/exception/AuthNotFoundException.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
- src/main/java/com/yello/server/domain/friend/controller/FriendController.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/annotation/AccessTokenUser.java
- src/main/java/com/yello/server/global/common/annotation/AccessTokenUserResolver.java
* resolves 
* @AccessTokenUser 구현
* 
*
> YEL-28 [feat] 인가 annotation 기능 추가

- src/main/java/com/yello/server/domain/friend/controller/FriendController.java
- src/main/java/com/yello/server/domain/user/service/UserServiceImpl.java
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/entity/VoteRepository.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
* resolves YEL-17
* AccessTokenUser를 이용한 인가 처리
*
> YEL-17 [update] AccessTokenUser를 이용한 인가 처리

- src/main/java/com/yello/server/domain/friend/controller/FriendController.java
- src/main/java/com/yello/server/domain/friend/dto/request/KakaoRecommendRequest.java
- src/main/java/com/yello/server/domain/friend/dto/response/Friend.java
- src/main/java/com/yello/server/domain/friend/dto/response/KakaoFriendResponse.java
- src/main/java/com/yello/server/domain/friend/service/FriendService.java
- src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
- src/main/java/com/yello/server/domain/user/entity/UserRepository.java
- src/main/java/com/yello/server/global/common/util/RestUtil.java
* resolves YEL-32
* kakao 친구 리스트 조회하기 구현
*
> YEL-32 [feat] kakao recommend friend list 조회

- src/main/java/com/yello/server/domain/friend/controller/FriendController.java
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
* resolves YEL-44
* update access token 적용
*
> YEL-44 [feat] update access token 적용

- src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
- src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
- src/main/java/com/yello/server/domain/question/dto/response/VoteAvailableResponse.java
- src/main/java/com/yello/server/domain/user/controller/UserController.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/common/annotation/AccessTokenUserResolver.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/main/java/com/yello/server/global/common/util/TimeUtil.java
- src/main/java/com/yello/server/global/configuration/SwaggerConfiguration.java
- src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
- src/main/java/com/yello/server/global/exception/ExceptionHandlerFilter.java
> YEL-45 [refactor] 코드 개선

- src/main/java/com/yello/server/domain/vote/dto/response/VoteContentVO.java
* resolves YEL-45
* NameFoot 파싱
*
> YEL-45 [update] NameFoot 파싱

- src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
* resolves YEL-45
* VoteDetailResponse에 포인트 추가
*
> YEL-45 [update] VoteDetailResponse에 포인트 추가

- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteCreateResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
* resolves YEL-46 
* 투표 생성시 포인트 전달
*
> YEL-46 [modify] create vote response

- src/main/java/com/yello/server/domain/vote/common/WeightedRandom.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
* resolves YEL-47 
* 가중치 수치 수정
*
> YEL-47 [modify] modify point weight

- src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
- src/main/java/com/yello/server/domain/authorization/dto/response/DepartmentSearchResponse.java
- src/main/java/com/yello/server/domain/authorization/dto/response/GroupNameSearchResponse.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
- src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
- src/main/java/com/yello/server/domain/group/entity/School.java
- src/main/java/com/yello/server/domain/group/entity/SchoolRepository.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
* resolves 
* 학교 학과 검색 API 구현
* 
*
> YEL-25 [feat] 학교 학과 검색 API 구현

- src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoFriend.java
- src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoFriendsInfo.java
- src/main/java/com/yello/server/domain/authorization/dto/kakao/KakaoTokenInfo.java
* resolves 
* 클라 측 테스트를 위해 kakao API case 변경
*
> YEL-50 [hotfix] 잠시 case 바꿈

- src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
- src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
- src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
* resolves 
* kakao token 의존성 제거
* yelloId valid 중복 비인가 처리
* 
*
> YEL-28 [fix] kakao token 의존성 제거

- src/main/java/com/yello/server/domain/friend/dto/response/FriendShuffleResponse.java
- src/main/java/com/yello/server/domain/question/dto/response/VoteAvailableResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/main/java/com/yello/server/global/common/util/TimeUtil.java
* resolves YEL-51
* 클라이언트 요청사항 해결
*
> [YEL-51] 타이머 40분 추가, shuffle에 yelloId 추가

- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteListResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
* resolves YEL-52
* 내 투표 전체 조회 API Response 수정
*
> YEL-52 [fix] 내 투표 전체 조회 API Response 수정

- src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
* resolves YEL-51 
* 학교 그룹 데이터 filter 수정
*
> YEL-51 [hotfix] 학교 그룹 데이터 filter

- .github/CODEOWNERS
- src/main/java/com/yello/server/domain/friend/controller/FriendController.java
- src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
* resolves 
* 친구의 친구를 찾아나선 문제 수정
* 응답 메세지 "유저 삭제" -> "친구 삭제" 로 변경
*
> YEL-45 [hotfix] 친구 전체 조회 로직 수정

- src/main/java/com/yello/server/domain/authorization/dto/response/DepartmentSearchResponse.java
- src/main/java/com/yello/server/domain/authorization/dto/response/GroupNameSearchResponse.java
- src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
- src/main/java/com/yello/server/domain/group/entity/SchoolRepository.java
* resolves 
- 학교 학과 검색 totalCount 수정
* 
*
> YEL-25 [hotfix] totalCount 수정

- src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
- src/main/java/com/yello/server/domain/friend/controller/FriendController.java
- src/main/java/com/yello/server/domain/friend/dto/response/FriendResponse.java
- src/main/java/com/yello/server/domain/friend/dto/response/RecommendFriendResponse.java
- src/main/java/com/yello/server/domain/friend/service/FriendService.java
- src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
- src/main/java/com/yello/server/domain/question/dto/response/VoteAvailableResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/main/java/com/yello/server/global/common/util/TimeUtil.java
> YEL-51 [fix] 타이머 수정

- src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
> YEL-51 [hotfix] 타이머 오류해결

- src/main/java/com/yello/server/domain/pay/controller/PayController.java
- src/main/java/com/yello/server/domain/pay/dto/request/PayCountRequest.java
- src/main/java/com/yello/server/domain/pay/entity/Pay.java
- src/main/java/com/yello/server/domain/pay/entity/PayRepository.java
- src/main/java/com/yello/server/domain/pay/sevice/PayService.java
- src/main/java/com/yello/server/domain/pay/sevice/PayServiceImpl.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
> YEL-48 [feat] pay change check

- docker/docker-compose.blue.yml
- docker/docker-compose.green.yml
> YEL-45 [fix] docker-compose TZ 세팅

- src/main/java/com/yello/server/domain/cooldown/response/KeywordCheckResponse.java
- src/main/java/com/yello/server/domain/cooldown/response/RevealNameResponse.java
- src/main/java/com/yello/server/domain/cooldown/response/VoteContentVO.java
- src/main/java/com/yello/server/domain/cooldown/response/VoteCreateResponse.java
- src/main/java/com/yello/server/domain/cooldown/response/VoteDetailResponse.java
- src/main/java/com/yello/server/domain/cooldown/response/VoteFriendResponse.java
- src/main/java/com/yello/server/domain/cooldown/response/VoteListResponse.java
- src/main/java/com/yello/server/domain/cooldown/response/VoteResponse.java
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
* resolves YEL-45
* FriendException 처리
*
> YEL-45 [update] FriendException 처리

- src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
- src/main/java/com/yello/server/domain/vote/dto/response/RevealNameResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
> YEL-51 [hotfix] 이름 부분확인 index dto 추가

- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
> YEL-51 [hotfix] keyword hint point 반영

- src/main/java/com/yello/server/domain/vote/entity/Vote.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
* resolves YEL-45
* 투표 읽음 처리 반영
*
> YEL-45 [fix] 투표 읽음 처리

- src/main/java/com/yello/server/domain/friend/dto/FriendsResponse.java
- src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
- src/main/java/com/yello/server/domain/user/controller/UserController.java
- src/main/java/com/yello/server/domain/user/dto/response/UserDetailResponse.java
- src/main/java/com/yello/server/domain/user/dto/response/UserResponse.java
- src/main/java/com/yello/server/domain/user/service/UserService.java
- src/main/java/com/yello/server/domain/user/service/UserServiceImpl.java
* resolves YEL-60
* 내 정보 조회 API
*
> YEL-60 [feat] 내 정보 조회 API

- src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
- src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
> YEL-51 [hotfix] recommendId null -> ""으로 수정

- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/common/WeightedRandom.java
- src/main/java/com/yello/server/domain/vote/service/VoteServiceImpl.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
> YEL-51 [fix] point weight 수정

- src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
- src/main/java/com/yello/server/domain/authorization/configuration/SecurityConfiguration.java
- src/main/java/com/yello/server/domain/authorization/configuration/WebMvcConfig.java
- src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
- src/main/java/com/yello/server/domain/authorization/dto/ServiceTokenVO.java
- src/main/java/com/yello/server/domain/authorization/exception/NotExpiredTokenForbiddenException.java
- src/main/java/com/yello/server/domain/authorization/exception/NotValidTokenForbiddenException.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
- src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/common/annotation/ServiceToken.java
- src/main/java/com/yello/server/global/common/annotation/ServiceTokenResolver.java
- src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
* resolves 
* YEL-49 토큰 재발급 API 구현
* 
*
> YEL-49 토큰 재발급 API 구현

- src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
> YEL-51 [hotfix] 카카오추천 친구 uuid 없는 값일경우 에러처리 제거

- src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
- src/main/java/com/yello/server/domain/authorization/dto/response/OnBoardingFriendResponse.java
- src/main/java/com/yello/server/domain/authorization/service/AuthServiceImpl.java
- src/main/java/com/yello/server/domain/friend/dto/response/FriendResponse.java
* resolves 
학번 추가, 온보딩 친구 추가 수정
* 학번 추가, 온보딩 친구 추가 수정
*
> YEL-51 [hotfix] 학번 추가, 온보딩 친구 추가 수정

- src/main/java/com/yello/server/domain/friend/service/FriendServiceImpl.java
* resolves 
YEL-51 [fix] 친구 추가 에러 해결
* 
*
> YEL-51 [fix] 친구 추가 에러 해결

- src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
> YEL-45 [chore] 필터 예외 코드 원복

- src/main/java/com/yello/server/domain/user/entity/User.java
* resolves YEL-51
* point 기본값 수정
*
> YEL-51 [fix] point 기본값 수정

- src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
* resolves YEL-51
* accessToken 기간 수정
*
> YEL-51 [fix] accessToken 기간 수정

- src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
* resolves 
* accessToekn 3minute로
*
> YEL-51 [fix] accessToekn 3minute로

- .gitignore
- build.gradle
- monitoring/docker-compose.monitor.yml
- monitoring/prometheus/config/prometheus.yml
- src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
* resolves YEL-72
* Prometheus를 이용한 시스템 자원 모니터링 지원하도록 설정
* Grafana를 통해 데이터 시각화 처리
* 환경설정 파일 업데이트
*
> YEL-72 [add] 서버 모니터링 시스템 구축

- build.gradle
- src/main/java/com/yello/server/domain/friend/controller/FriendController.java
- src/main/java/com/yello/server/domain/pay/controller/PayController.java
- src/main/java/com/yello/server/domain/user/controller/UserController.java
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/global/common/annotation/AccessTokenUser.java
- src/main/java/com/yello/server/global/configuration/SwaggerConfiguration.java
* resolves YEL-70
* 요청 헤더에 @AccessTokenUser의 엔티티가 그대로 보여지고 있던 문제를 커스텀 어노테이션 상단에 hidden 옵션을 주어 처리
* 스웨거 내부에 인가 처리 방식 추가
* 스웨거 의존성 버전 수정 (`build.gradle` 참고)
* 기타 코드 컨벤션에 맞추어 정리
*
> YEL-70 [docs] 스웨거 개선

- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
> YEL-80 [hotfix] Update ConstantUtil.java

- src/main/java/com/yello/server/domain/authorization/dto/request/OAuthRequest.java
- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
- src/main/java/com/yello/server/domain/user/service/UserService.java
- src/test/java/com/yello/server/small/domain/user/UserServiceTest.java
> YEL-88 [update] 요청 필드 수정 및 탈퇴 시 디바이스 삭제 처리

- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteCreateResponse.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteCreateVO.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
> YEL-88 [fix] 투표 생성 응답값 수정

- src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
- src/main/java/com/yello/server/domain/user/entity/Subscribe.java
- src/main/java/com/yello/server/domain/user/entity/SubscribeConverter.java
- src/main/java/com/yello/server/domain/user/entity/User.java
* resolves YEL-90 
* entity 수정 반영
*
> YEL-90 [feat] entity 수정 반영

- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/user/service/UserService.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
- src/main/java/com/yello/server/infrastructure/redis/repository/TokenRepository.java
- src/main/java/com/yello/server/infrastructure/redis/repository/TokenRepositoryImpl.java
- src/test/java/com/yello/server/small/domain/user/UserServiceTest.java
- src/test/java/com/yello/server/small/global/firebase/NotificationFcmServiceTest.java
- src/test/java/com/yello/server/small/global/redis/FakeTokenRepository.java
> YEL-88 [update] User 엔티티 변경에 따른 푸시 알림 로직 수정

- src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
- src/main/java/com/yello/server/domain/user/entity/User.java
> YEL-90 [feat] subscribe 수정

- src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
- src/main/java/com/yello/server/domain/user/entity/User.java
> YEL-90 [feat] subscribe, minute

- src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
- src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
- src/main/java/com/yello/server/domain/user/entity/User.java
> YEL-90 [develop]

- src/main/java/com/yello/server/domain/user/entity/User.java
> YEL-90 [feat] user 수정

- src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
- src/main/java/com/yello/server/domain/user/entity/User.java
> YEL-90 [develop] develop to staging

- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
> YEL-88 [fix] 푸시 알림 메세지 받는 사람 기준으로 보내지는 문제 해결

- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteUnreadCountResponse.java
- src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
- src/main/java/com/yello/server/domain/vote/repository/VoteRepository.java
- src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/test/java/com/yello/server/small/domain/vote/FakeVoteRepository.java
- src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
> YEL-89 [feat] 읽지 않은 투표 개수 조회 API

- build.gradle
- src/main/java/com/yello/server/domain/question/entity/Question.java
- src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationMessage.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
> YEL-88 [update] 투표 알림 메세지 변경

- src/main/java/com/yello/server/domain/question/entity/Question.java
> YEL-88 [feat] nameHead가 없는 경우 처리

- src/main/java/com/yello/server/domain/authorization/dto/request/SignUpRequest.java
- src/main/java/com/yello/server/domain/friend/controller/FriendController.java
- src/main/java/com/yello/server/domain/friend/dto/response/SearchFriendResponse.java
- src/main/java/com/yello/server/domain/friend/dto/response/SearchFriendVO.java
- src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
- src/main/java/com/yello/server/domain/friend/service/FriendService.java
- src/main/java/com/yello/server/domain/group/repository/SchoolJpaRepository.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
* resolves YEL-93
* 친구 검색 API 개발
* 영어인 경우 -> yelloId으로 가져오기
* 한글인 경우 -> name으로 가져오기
* sort 조건 
(같은 학교 -> 이름순, 다른 학교 ->  나이순)
> YEL-93 [feat] 친구 검색 API 개발

- src/main/java/com/yello/server/domain/friend/dto/response/RecommendFriendResponse.java
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteFriendResponse.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteFriendVO.java
- src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
- src/main/java/com/yello/server/domain/vote/repository/VoteRepository.java
- src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/test/java/com/yello/server/small/domain/vote/FakeVoteRepository.java
- src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
* resolves YEL-97, YEL-79
* 친구 투표 조회 API totalCount 필드 추가
* 스웨거 fix
* 
*
> YEL-97 [fix] 친구 투표 조회 API totalCount 필드 추가

- src/main/java/com/yello/server/domain/authorization/dto/response/OAuthResponse.java
- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
* resolves YEL-99
* [fix] 재로그인 여부 필드 추가
* 
*
> YEL-99 [fix] 재로그인 여부 필드 추가

- src/main/java/com/yello/server/domain/friend/controller/FriendController.java
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
> YEL-93 [fix] pagination 수정

- src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
- src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
* resolves YEL-101 
* 친구 검색 test
> YEL-101 [test] 친구 검색 test

- src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
- src/main/java/com/yello/server/domain/purchase/entity/Gateway.java
- src/main/java/com/yello/server/domain/purchase/entity/GatewayConverter.java
- src/main/java/com/yello/server/domain/purchase/entity/ProductType.java
- src/main/java/com/yello/server/domain/purchase/entity/ProductTypeConverter.java
- src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
> YEL-103 [feat] purchase entity 개발

- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
> YEL-103 [hotfix] soft delete error 해결

- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/configuration/RabbitmqConfiguration.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/dto/response/VoteAvailableQueueResponse.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRabbitRepository.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRepository.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/service/ConsumerRabbitmqService.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/service/ConsumerService.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/service/ProducerRabbitmqService.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/service/ProducerService.java
* resolves YEL-88
* 스프링 메세지큐 구현체로 RabbitMQ 사용
* Producer, Consumer 구현
*
> YEL-88 [feat] 40분 대기열 후 푸시 알림 전송

- src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
- src/main/java/com/yello/server/domain/friend/entity/Friend.java
- src/main/java/com/yello/server/domain/group/entity/School.java
- src/main/java/com/yello/server/domain/user/entity/User.java
* resolves 
* YEL-106 [fix] unique 설정
* 
*
> YEL-106 [fix] unique 설정

- src/main/java/com/yello/server/domain/authorization/JwtTokenProvider.java
- src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
- src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/yello/server/domain/friend/service/FriendService.java
> YEL-108 [feat] 친구 추가 로직 수정

- src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceipt.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceiptResponse.java
- src/main/java/com/yello/server/global/common/util/AppleUtil.java
> YEL-108 [feat] apple util 생성

- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteListResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
* resolves YEL-107
* 쪽지 상세뷰, 내쪽지 전체 열람권 개수 
*
> YEL-107 [feat] 열람권 개수 추가

- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
- src/main/java/com/yello/server/domain/question/entity/Question.java
- src/main/java/com/yello/server/domain/question/repository/QuestionJpaRepository.java
- src/main/java/com/yello/server/domain/question/repository/QuestionRepository.java
- src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/entity/Vote.java
- src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
- src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
- src/test/java/com/yello/server/small/domain/friend/FakeFriendRepository.java
- src/test/java/com/yello/server/small/domain/question/FakeQuestionRepository.java
* resolves
* YEL-96 [feat] 첫 쪽지 구현
* 
*
> YEL-96 [feat] 첫 쪽지 구현

- src/main/java/com/yello/server/domain/friend/repository/FriendJpaRepository.java
- src/main/java/com/yello/server/domain/friend/repository/FriendRepository.java
- src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceipt.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/AppleVerifyReceiptResponse.java
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteListResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/util/AppleUtil.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
- src/test/java/com/yello/server/small/domain/friend/FakeFriendRepository.java
- src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
- src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
- src/test/java/com/yello/server/small/global/rabbitmq/FakeMessageQueueRepository.java
- src/test/java/com/yello/server/small/global/rabbitmq/FakeProducerService.java
* resolves 
- YEL-109 [feat] , 제거
* 
*
> YEL-109 [feat] , 제거

- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/entity/Vote.java
* resolves 
* YEL-95 [feat] nameHint -3, 옐로팀 이름 수정
* 
*
> YEL-95 [feat] nameHint -3, 옐로팀 이름 수정

- src/main/java/com/yello/server/domain/question/dto/response/QuestionForVoteResponse.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
> YEL-92 [feat] 투표 조회하기 구독여부 추가

- src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
* resolves 
* YEL-112 [feat] 투표 상세 subscribe 필드 추가
* 
*
> YEL-112 [feat] 투표 상세 subscribe 필드 추가

- .github/workflows/test.yml
* resolves 
* YEL-100 [fix] test CI 수정
* 
*
> YEL-100 [fix] test CI 수정

- .github/workflows/test.yml
- src/main/java/com/yello/server/domain/vote/dto/response/VoteDetailResponse.java
* resolves 
* YEL-112 [staging] ENUM -> Boolean 수정
* 
*
> YEL-112 [staging] ENUM -> Boolean 수정

- src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
- src/main/java/com/yello/server/domain/purchase/dto/response/UserSubscribeNeededResponse.java
- src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/user/controller/UserController.java
- src/main/java/com/yello/server/domain/user/service/UserService.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/test/java/com/yello/server/small/domain/purchase/FakePurchaseRepository.java
- src/test/java/com/yello/server/small/domain/purchase/PurchaseTest.java
- src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
* resolves 
* YEL-98 [feat] 구독 연장 유도 필요 여부 확인 API 추가
* 
*
> YEL-98 [feat] 구독 연장 유도 필요 여부 확인 API 추가

- src/main/java/com/yello/server/domain/user/controller/UserController.java
- src/main/java/com/yello/server/domain/user/dto/request/UserDeviceTokenRequest.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/yello/server/domain/user/service/UserService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/common/dto/EmptyObject.java
* resolves 
* YEL-114 [feat] deviceToken 업데이트 API 추가
* 
*
> YEL-114 [feat] deviceToken 업데이트 API 추가

- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/test/java/com/yello/server/small/domain/user/FakeUserRepository.java
* resolves 
* YEL-115 [fix] 둘러보기에 첫쪽지 제외
* 
*
> YEL-115 [fix] 둘러보기에 첫쪽지 제외

- build.gradle
- src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
- src/main/java/com/yello/server/global/common/util/SlackUtil.java
- src/main/java/com/yello/server/global/configuration/ThreadPoolConfiguration.java
- src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
* resolves 
* YEL-113 [feat] 500에러 슬랙 알람 추가
* 
*
> YEL-113 [feat] 500에러 슬랙 알람 추가

- .github/workflows/test.yml
> YEL-110 [fix] ci 수정

- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/dto/response/RevealFullNameResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
* resolves YEL-123 
* 이름 전체 공개 API 구현
*
> YEL-123 [feat] 이름 전체 공개 API 구현

- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/domain/vote/dto/response/RevealFullNameResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/util/AppleUtil.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
> YEL-123 [develop] 배포

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- .gitignore
- build.gradle
- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
- src/main/java/com/yello/server/global/HealthCheckController.java
- src/main/java/com/yello/server/global/common/dto/response/GoogleInAppGetResponse.java
- src/main/java/com/yello/server/global/common/dto/response/GoogleTokenIssueResponse.java
- src/main/java/com/yello/server/global/common/entity/GoogleToken.java
- src/main/java/com/yello/server/global/common/repository/GoogleTokenJpaRepository.java
- src/main/java/com/yello/server/global/common/repository/GoogleTokenRepository.java
- src/main/java/com/yello/server/global/common/repository/GoogleTokenRepositoryImpl.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/main/java/com/yello/server/global/common/util/RestUtil.java
* resolves 
* YEL-109 [feat] Google Rest Util 추가
* 
*
> YEL-109 [feat] Google Rest Util 추가

- src/main/java/com/yello/server/domain/vote/controller/VoteController.java
> YEL-104 [feat] 투표 이름 전체 조회 수정

- src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
- src/main/java/com/yello/server/domain/cooldown/entity/Cooldown.java
- src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepository.java
- src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepositoryImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/infrastructure/firebase/dto/NotificationType.java
- src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationMessage.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationService.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/dto/response/VoteAvailableQueueResponse.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRabbitRepository.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/repository/MessageQueueRepository.java
- src/main/java/com/yello/server/infrastructure/rabbitmq/service/ProducerRabbitmqService.java
- src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
- src/test/java/com/yello/server/small/domain/cooldown/FakeCooldownRepository.java
- src/test/java/com/yello/server/small/global/rabbitmq/FakeMessageQueueRepository.java
> YEL-124 [add] 푸시 알림 관련 도메인 로직 수정

- src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
> YEL-104 [feat] 친구 셔플 테스트

- src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
- src/main/java/com/yello/server/domain/purchase/dto/request/GoogleSubscriptionV2GetRequest.java
- src/main/java/com/yello/server/domain/purchase/dto/response/GoogleSubscriptionV2GetResponse.java
- src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
- src/main/java/com/yello/server/domain/purchase/exception/GoogleBadRequestException.java
- src/main/java/com/yello/server/domain/purchase/exception/GoogleTokenNotFoundException.java
- src/main/java/com/yello/server/domain/purchase/exception/GoogleTokenServerErrorException.java
- src/main/java/com/yello/server/domain/purchase/exception/PurchaseConflictException.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
- src/main/java/com/yello/server/global/HealthCheckController.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/common/entity/GoogleToken.java
- src/main/java/com/yello/server/global/common/repository/GoogleTokenRepository.java
- src/main/java/com/yello/server/global/common/repository/GoogleTokenRepositoryImpl.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/main/java/com/yello/server/global/common/util/RestUtil.java
- src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
- src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
* resolves 
* YEL-95 [feat] 구글 구독 확인 API 구현
* 
*
> YEL-95 [feat] 구글 구독 확인 API 구현

- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
> YEL-128 [fix] build 에러 수정

- src/main/java/com/yello/server/domain/friend/service/FriendService.java
- src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
- src/test/java/com/yello/server/small/domain/vote/FakeVoteManager.java
> YEL-132 [hotfix] shuffle 시 불변 객체를 피하도록 수정

- src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
- src/test/java/com/yello/server/small/domain/authorization/AuthManagerTest.java
- src/test/java/com/yello/server/small/domain/authorization/AuthServiceTest.java
- src/test/java/com/yello/server/small/domain/friend/FriendManagerTest.java
- src/test/java/com/yello/server/small/domain/friend/FriendServiceTest.java
- src/test/java/com/yello/server/small/domain/purchase/PurchaseServiceTest.java
- src/test/java/com/yello/server/small/domain/user/UserManagerTest.java
- src/test/java/com/yello/server/small/domain/user/UserServiceTest.java
- src/test/java/com/yello/server/small/domain/vote/VoteManagerTest.java
- src/test/java/com/yello/server/small/domain/vote/VoteServiceTest.java
- src/test/java/com/yello/server/util/TestDataUtil.java
> YEL-134 [test] 목데이터를 위한 테스트 유틸 클래스 작성 및 테스트 코드 수정

- src/main/java/com/yello/server/domain/question/entity/Question.java
> YEL-135 [update] 푸시 알림 메세지 변경

- src/main/java/com/yello/server/domain/friend/service/FriendService.java
> YEL-111 [fix] 친구 검색시 빈값인 경우 빈배열 제공

- src/main/java/com/yello/server/domain/vote/dto/response/VoteCountVO.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteListResponse.java
- src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
- src/main/java/com/yello/server/domain/vote/repository/VoteRepository.java
- src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/test/java/com/yello/server/small/domain/vote/FakeVoteRepository.java
> YEL-138 [modify] 내 쪽지 count data 추가

- .github/workflows/deploy-test.yml
- .github/workflows/deploy.yml
- src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
> YEL-132 [hotfix] 상수처리

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/global/common/util/AppleUtil.java
> YEL-140 [modify] apple in app verify 로직 수정

- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
* resolves 
* YEL-132 [hotfix] if문에서 case문으로 바꿈
* 
*
> YEL-132 [hotfix] if문에서 case문으로 바꿈

- build.gradle
> YEL-139 [test] 빌드 스크립트 수정

- src/main/java/com/yello/server/domain/purchase/dto/apple/AppleOrderResponse.java
- src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
> YEL-144 [fix] apple 결제 json 오류 수정

- src/docs/asciidoc/google.adoc
> YEL-139 [test] 구글 결제 관련 명세서 수정

- src/main/resources/static/docs/check-vote-available.html
- src/main/resources/static/docs/google.html
- src/main/resources/static/docs/index.html
> YEL-139 [docs] 명세서 오류 수정

- src/main/java/com/yello/server/domain/friend/service/FriendService.java
> YEL-146 [fix] 친구 삭제 500에러 수정

- src/main/java/com/yello/server/domain/admin/controller/AdminController.java
- src/main/java/com/yello/server/domain/admin/dto/response/AdminCooldownContentVO.java
- src/main/java/com/yello/server/domain/admin/dto/response/AdminCooldownResponse.java
- src/main/java/com/yello/server/domain/admin/dto/response/AdminUserContentVO.java
- src/main/java/com/yello/server/domain/admin/dto/response/AdminUserResponse.java
- src/main/java/com/yello/server/domain/admin/dto/response/AdminUserSearchResponse.java
- src/main/java/com/yello/server/domain/admin/entity/UserAdmin.java
- src/main/java/com/yello/server/domain/admin/exception/UserAdminNotFoundException.java
- src/main/java/com/yello/server/domain/admin/repository/UserAdminJpaRepository.java
- src/main/java/com/yello/server/domain/admin/repository/UserAdminRepository.java
- src/main/java/com/yello/server/domain/admin/repository/UserAdminRepositoryImpl.java
- src/main/java/com/yello/server/domain/admin/service/AdminService.java
- src/main/java/com/yello/server/domain/cooldown/repository/CooldownJpaRepository.java
- src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepository.java
- src/main/java/com/yello/server/domain/cooldown/repository/CooldownRepositoryImpl.java
- src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/yello/server/domain/user/service/UserService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/common/factory/TimeFactory.java
- src/test/java/com/yello/server/domain/cooldown/FakeCooldownRepository.java
- src/test/java/com/yello/server/domain/user/FakeUserRepository.java
* resolves 
* 유저, 쿨다운 조회 및 삭제
* 
*
> YEL-147 [feat] admin 1차 구현

- build.gradle
- src/main/java/com/yello/server/domain/purchase/dto/apple/TransactionInfoResponse.java
- src/main/java/com/yello/server/domain/purchase/dto/response/AppleJwsTransactionResponse.java
- src/main/java/com/yello/server/domain/purchase/exception/AppleBadRequestException.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/factory/TokenFactory.java
- src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
- src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
- src/main/java/com/yello/server/infrastructure/client/ApiWebClient.java
- src/main/java/com/yello/server/infrastructure/client/AppleApiWebClient.java
- src/test/java/com/yello/server/domain/purchase/FakeAppleApiWebClient.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
- src/test/java/com/yello/server/domain/purchase/FakeTokenFactory.java
> YEL-148 [fix] apple verify 수정

- src/main/java/com/yello/server/domain/admin/configuration/AdminWebConfig.java
- src/main/java/com/yello/server/domain/admin/controller/AdminController.java
> YEL-147 [feat] cors 설정

- src/main/java/com/yello/server/domain/friend/service/FriendService.java
- src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/test/java/com/yello/server/domain/user/FakeUserRepository.java
> YEL-149 [fix] 친구 검색하기 로직 수정

- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
- src/main/java/com/yello/server/global/common/dto/MultiReadHttpServletRequest.java
- src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
- src/main/java/com/yello/server/global/exception/ExceptionHandlerFilter.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
- src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
* resolves 
* YEL-132 [hotfix] 회원가입 에러 처리 - DeviceToken 처리
* 
*
> YEL-132 [hotfix] 회원가입 에러 처리 - DeviceToken 처리

- src/main/java/com/yello/server/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
* resolves 
* YEL-132 [hotfix] repositoryImpl @Transactional 제거
* 
*
> YEL-132 [hotfix] repositoryImpl @Transactional 제거

- build.gradle
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
- src/main/java/com/yello/server/global/common/factory/TokenFactory.java
- src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
- src/test/java/com/yello/server/domain/purchase/FakeTokenFactory.java
* resolves YEL-148
* jwt token 디코딩하여 알맞은 transaction인지 확인
*
> YEL-148 [fix] decode payload

- build.gradle
- src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
- src/main/java/com/yello/server/global/HealthCheckController.java
- src/main/java/com/yello/server/global/common/dto/MultiReadHttpServletRequest.java
- src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
> YEL-150 [fix] Slack 메세지에 Header 및 에러 class 추가

- src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
- src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
- src/test/java/com/yello/server/domain/user/FakeUserRepository.java
* resolves 
* [YEL-150 [fix] 구독 중 키워드 확인시 포인트 차감 수정](https://github.com/team-yello/YELLO-Server/commit/947f2e605891d52ac413e7d3c36a942ca56d41eb)
* 
*
> YEL-150 [fix] 구독 중 키워드 확인시 포인트 차감 수정

- src/main/java/com/yello/server/domain/admin/controller/AdminController.java
- src/main/java/com/yello/server/domain/admin/dto/request/AdminLoginRequest.java
- src/main/java/com/yello/server/domain/admin/dto/response/AdminLoginResponse.java
- src/main/java/com/yello/server/domain/admin/service/AdminService.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/user/service/UserManager.java
- src/main/java/com/yello/server/domain/user/service/UserManagerImpl.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/test/java/com/yello/server/domain/user/FakeUserManager.java
* resolves 
* YEL-151 [feat] 어드민 로그인 간소화
* 
*
> YEL-151 [feat] 어드민 로그인 간소화

- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
> YEL-152 [fix] 구글 구독시 열람권 3개 추가

- src/main/java/com/yello/server/domain/friend/service/FriendService.java
- src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/test/java/com/yello/server/domain/user/FakeUserRepository.java
> YEL-153 [fix] 학과친구 학교친구 추천으로 수정

- src/main/java/com/yello/server/domain/admin/controller/AdminController.java
- src/main/java/com/yello/server/domain/admin/dto/request/AdminUserDetailRequest.java
- src/main/java/com/yello/server/domain/admin/dto/response/AdminUserDetailResponse.java
- src/main/java/com/yello/server/domain/admin/service/AdminService.java
- src/main/java/com/yello/server/domain/purchase/controller/PurchaseController.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
- src/test/java/com/yello/server/domain/user/FakeUserRepository.java
* resolves 
* [YEL-158 [feat] 어드민 유저 디테일 조회 수정 및 어드민 비밀번호 변경](https://github.com/team-yello/YELLO-Server/commit/3cc9d0ed58dafa64617b0e9f2c14590104c4b227)
* 
*
> YEL-158 [feat] 어드민 유저 디테일 조회 수정 및 어드민 비밀번호 변경

- src/main/java/com/yello/server/domain/admin/controller/AdminController.java
- src/main/java/com/yello/server/domain/admin/exception/UserAdminBadRequestException.java
- src/main/java/com/yello/server/domain/admin/service/AdminService.java
- src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
- src/test/java/com/yello/server/domain/user/FakeUserRepository.java
* resolves 
* YEL-159 [feat] 어드민 이름 검색 추가
* 
*
> YEL-159 [feat] 어드민 이름 검색 추가

- src/main/java/com/yello/server/domain/admin/service/AdminService.java
- src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
- src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/yello/server/infrastructure/slack/annotation/SlackSignUpNotification.java
- src/main/java/com/yello/server/infrastructure/slack/aspect/SlackSignUpNotificationAspect.java
- src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
- src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
- src/test/java/com/yello/server/domain/user/FakeUserRepository.java
* resolves 
* YEL-161 [feat] 회원가입 슬랙 알림 추가
* 
*
> YEL-161 [feat] 회원가입 슬랙 알림 추가

- src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
- src/main/java/com/yello/server/domain/purchase/controller/PurchaseNotificationController.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/AppleNotificationPayloadVO.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadDataVO.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadSummaryVO.java
- src/main/java/com/yello/server/domain/purchase/dto/request/AppleNotificationRequest.java
- src/main/java/com/yello/server/domain/purchase/dto/response/AppleNotificationResponse.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
- src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
> YEL-154 [feat] apple notification - 구독 취소한 경우

- src/main/java/com/yello/server/domain/authorization/filter/JwtExceptionFilter.java
- src/main/java/com/yello/server/domain/authorization/filter/JwtFilter.java
- src/main/java/com/yello/server/domain/purchase/controller/PurchaseNotificationController.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/AppleNotificationPayloadVO.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadDataVO.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadSummaryVO.java
- src/main/java/com/yello/server/domain/purchase/dto/request/AppleNotificationRequest.java
- src/main/java/com/yello/server/domain/purchase/dto/response/AppleNotificationResponse.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
- src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
> YEL-154 [develop] apple notification 개발 서버 배포

- src/main/java/com/yello/server/domain/purchase/dto/apple/AppleNotificationPayloadVO.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePayloadDataVO.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
- src/main/java/com/yello/server/global/common/factory/TokenFactoryImpl.java
> YEL-154 [fix] json parse 수정

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
> YEL-154 [fix] decode 수정

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
> YEL-154 [develop] 배포

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
> YEL-154 [fix] json null 처리

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/global/common/factory/DecodeTokenFactory.java
> YEL-154 [develop]

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
> YEL-154 [feat] 에러 분기처리

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
> YEL-154 [develop] apple 분기처리 배포

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
> YEL-154 [fix] test notification 수정

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
> YEL-154 [develop] 서버 배포

- src/main/java/com/yello/server/domain/user/entity/User.java
> YEL-153 [hotfix] deviceToken 공스트링 처리

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
- src/test/java/com/yello/server/domain/user/small/UserTest.java
* resolves YEL-155
* NotificationType이 refund일 경우 처리
*
> YEL-155 [feat] apple refund 처리

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
- src/test/java/com/yello/server/domain/user/small/UserTest.java
> YEL-155 [develop] 개발 서버 배포

- src/main/java/com/yello/server/domain/friend/service/FriendService.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteAvailableResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteManager.java
- src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/friend/small/FriendServiceTest.java
- src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
- src/test/java/com/yello/server/domain/vote/medium/VoteControllerTest.java
> YEL-162 [feat] 투표 수정사항 반영

- src/main/java/com/yello/server/domain/friend/service/FriendService.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteAvailableResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteManager.java
- src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/friend/small/FriendServiceTest.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
- src/test/java/com/yello/server/domain/user/small/UserTest.java
- src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
- src/test/java/com/yello/server/domain/vote/medium/VoteControllerTest.java
> YEL-162 [deploy] v1.196

- src/main/java/com/yello/server/domain/friend/service/FriendService.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteAvailableResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteManager.java
- src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/friend/small/FriendServiceTest.java
- src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
- src/test/java/com/yello/server/domain/vote/medium/VoteControllerTest.java
Reverts team-yello/YELLO-Server#325
> Revert "YEL-162 [feat] 투표 수정사항 반영"

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
- src/test/java/com/yello/server/domain/user/small/UserTest.java
Reverts team-yello/YELLO-Server#323
> Revert "YEL-155 [feat] apple refund 처리"

- src/main/java/com/yello/server/domain/friend/service/FriendService.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteAvailableResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteManager.java
- src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/friend/small/FriendServiceTest.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
- src/test/java/com/yello/server/domain/user/small/UserTest.java
- src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
- src/test/java/com/yello/server/domain/vote/medium/VoteControllerTest.java
> Revert "v1.195"

- src/main/java/com/yello/server/domain/friend/service/FriendService.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteAvailableResponse.java
- src/main/java/com/yello/server/domain/vote/service/VoteManager.java
- src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/friend/small/FriendServiceTest.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
- src/test/java/com/yello/server/domain/user/small/UserTest.java
- src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
- src/test/java/com/yello/server/domain/vote/medium/VoteControllerTest.java
> Revert "v1.195" of main

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
- src/test/java/com/yello/server/domain/user/small/UserTest.java
> YEL-155 [fix] revert

- src/main/java/com/yello/server/domain/admin/controller/AdminController.java
- src/main/java/com/yello/server/domain/admin/dto/request/AdminQuestionVoteContentVO.java
- src/main/java/com/yello/server/domain/admin/dto/request/AdminQuestionVoteRequest.java
- src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionContentVO.java
- src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionDetailResponse.java
- src/main/java/com/yello/server/domain/admin/dto/response/AdminQuestionResponse.java
- src/main/java/com/yello/server/domain/admin/dto/response/AdminUserContentVO.java
- src/main/java/com/yello/server/domain/admin/service/AdminService.java
- src/main/java/com/yello/server/domain/question/repository/QuestionRepository.java
- src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteManagerImpl.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
- src/test/java/com/yello/server/domain/question/FakeQuestionRepository.java
- src/test/java/com/yello/server/domain/user/FakeUserRepository.java
- src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
> YEL-163 [feat] 어드민 투표 API 구현

- src/main/java/com/yello/server/domain/authorization/controller/AuthController.java
- src/main/java/com/yello/server/domain/authorization/dto/response/ClassNameSearchResponse.java
- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
- src/main/java/com/yello/server/domain/friend/dto/response/FriendResponse.java
- src/main/java/com/yello/server/domain/friend/dto/response/SearchFriendVO.java
- src/main/java/com/yello/server/domain/group/entity/School.java
- src/main/java/com/yello/server/domain/group/entity/SchoolType.java
- src/main/java/com/yello/server/domain/group/entity/SchoolTypeConverter.java
- src/main/java/com/yello/server/domain/group/repository/SchoolJpaRepository.java
- src/main/java/com/yello/server/domain/group/repository/SchoolRepository.java
- src/main/java/com/yello/server/domain/group/repository/SchoolRepositoryImpl.java
- src/main/java/com/yello/server/domain/user/dto/response/UserDetailResponse.java
- src/main/java/com/yello/server/domain/user/dto/response/UserResponse.java
- src/main/java/com/yello/server/domain/user/entity/User.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/test/java/com/yello/server/domain/authorization/medium/AuthControllerTest.java
- src/test/java/com/yello/server/domain/group/FakeSchoolRepository.java
> YEL-163 [feat] 대학생, 고등학생 구분

- src/main/java/com/yello/server/domain/admin/controller/AdminController.java
- src/main/java/com/yello/server/domain/admin/service/AdminService.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationCustomMessage.java
- src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationMessage.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationService.java
> YEL-163 [deploy] v1.198 hotfix!!!

- src/main/java/com/yello/server/domain/admin/controller/AdminController.java
- src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
> YEL-166 [fix] 내림차순 정렬

- src/main/java/com/yello/server/domain/admin/controller/AdminController.java
- src/main/java/com/yello/server/domain/admin/service/AdminService.java
- src/main/java/com/yello/server/domain/purchase/dto/apple/AppleNotificationPayloadVO.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/global/common/factory/PaginationFactory.java
- src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationCustomMessage.java
- src/main/java/com/yello/server/infrastructure/firebase/dto/request/NotificationMessage.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationService.java
> YEL-169 [fix] notification 수정

- src/main/java/com/yello/server/domain/purchase/controller/PurchaseNotificationController.java
- src/main/java/com/yello/server/infrastructure/slack/annotation/SlackApplePurchaseNotification.java
- src/main/java/com/yello/server/infrastructure/slack/aspect/SlackApplePurchaseNotificationAspect.java
- src/main/java/com/yello/server/infrastructure/slack/configuration/SlackConfiguration.java
- src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
* resolves YEL-170 
* 애플에서 보낸 알림을 슬랙 알림으로 볼 수 있도록 구현했습니다.
* 애플에서 구독 취소, 구독, 환불 등에 대한 알림을 보냅니다.
*
> YEL-170 [feat] apple notification slack webhook

- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/infrastructure/slack/dto/response/SlackAppleNotificationResponse.java
- src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
> YEL-170 [modify] slack webhook request body 값 수정

- src/main/java/com/yello/server/domain/purchase/dto/apple/ApplePurchaseVO.java
- src/main/java/com/yello/server/domain/purchase/dto/response/AppleJwsTransactionResponse.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManager.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseManager.java
* resolves YEL-171 
* apple 구독 취소, 만료, 갱신 로직 구현
*
> YEL-171 [feat] apple 구독 취소, 만료, 갱신 로직 구현

- src/main/java/com/yello/server/domain/group/entity/UserGroupData.java
- src/main/java/com/yello/server/domain/group/entity/UserGroupDataTag.java
- src/main/java/com/yello/server/domain/group/entity/UserGroupDataTagConterver.java
* resolves 
* YEL-173 [feat] 유저 그룹 별 추가 정보 테이블 추가
* `key`가 mysql 예약어라서 `tag`로 변경함
* 
*
> YEL-173 [feat] 유저 그룹 별 추가 정보 테이블 추가

- src/main/java/com/yello/server/domain/group/entity/UserGroupData.java
- src/main/java/com/yello/server/domain/question/entity/QuestionGroupType.java
- src/main/java/com/yello/server/domain/question/repository/QuestionGroupTypeJpaRepository.java
- src/main/java/com/yello/server/domain/question/repository/QuestionGroupTypeRepository.java
- src/main/java/com/yello/server/domain/question/repository/QuestionGroupTypeRepositoryImpl.java
- src/main/java/com/yello/server/domain/question/repository/QuestionJpaRepository.java
- src/main/java/com/yello/server/domain/question/repository/QuestionRepository.java
- src/main/java/com/yello/server/domain/question/repository/QuestionRepositoryImpl.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/test/java/com/yello/server/domain/authorization/small/AuthManagerTest.java
- src/test/java/com/yello/server/domain/authorization/small/AuthServiceTest.java
- src/test/java/com/yello/server/domain/friend/small/FriendServiceTest.java
- src/test/java/com/yello/server/domain/question/FakeQuestionGroupTypeRepository.java
- src/test/java/com/yello/server/domain/user/small/UserServiceTest.java
- src/test/java/com/yello/server/domain/vote/FakeVoteManager.java
- src/test/java/com/yello/server/domain/vote/small/VoteManagerTest.java
- src/test/java/com/yello/server/domain/vote/small/VoteServiceTest.java
- src/test/java/com/yello/server/infrastructure/firebase/small/FcmManagerTest.java
- src/test/java/com/yello/server/util/TestDataEntityUtil.java
- src/test/java/com/yello/server/util/TestDataRepositoryUtil.java
- src/test/java/com/yello/server/util/TestDataUtil.java
> YEL-174 [feat] 고등학교,대학교 질문 다르게 매핑

- src/main/java/com/yello/server/domain/purchase/controller/PurchaseNotificationController.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
> YEL-176 [feat] google noti 테스트

- src/main/java/com/yello/server/domain/purchase/dto/request/google/DeveloperNotification.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
> YEL-176 [feat] 오류 수정 및 로그 추가

- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
> YEL-176 [feat] noti 종류별 purchase 접근 로직 픽스

- src/main/java/com/yello/server/domain/purchase/dto/request/google/SubscriptionNotification.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
> YEL-176 [feat] field 이름 수정

- src/main/java/com/yello/server/domain/purchase/dto/request/google/DeveloperNotification.java
- src/main/java/com/yello/server/domain/purchase/dto/request/google/SubscriptionNotification.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseService.java
> YEL-176 [feat] field 이름 수

- src/main/java/com/yello/server/domain/purchase/dto/request/google/OneTimeProductNotificationType.java
- src/main/java/com/yello/server/domain/purchase/dto/request/google/SubscriptionNotificationType.java
> YEL-176 [feat] Gson @SerializedName 추가

- src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
- src/main/java/com/yello/server/domain/purchase/service/PurchaseManagerImpl.java
* resolves YEL-177
* 애플 결제 raw data 칼럼 수정
* 애플 알림 state 반영
*
> YEL-177 [hotfix] apple pay column fix

- src/main/java/com/yello/server/domain/authorization/service/TokenJwtProvider.java
> 1.2 [hotfix] 토큰 시간 변경

- src/main/java/com/yello/server/domain/authorization/service/TokenJwtProvider.java
This reverts commit d2ffe90fca0858e31c50383d613771815d84d36e.
* resolves 
* 
*
> 1.2 [hotfix] Revert "1.2 [hotfix] 토큰 시간 변경"

- src/main/java/com/yello/server/domain/authorization/service/TokenJwtProvider.java
This reverts commit 7f94f3e42ad2f1fb2d233cf718c26c5bc9e3c9fe.
* resolves 
* 
*
> 1.2 [hotfix] Revert "1.2 [hotfix] Revert "1.2 [hotfix] 토큰 시간 변경""

- src/main/java/com/yello/server/domain/authorization/service/AuthManagerImpl.java
- src/main/java/com/yello/server/domain/vote/dto/response/VoteFriendVO.java
* resolves YEL-178
* 타임라인에 프로필 이미지 추가
*
> YEL-178 [fix] 타임라인에 프로필 이미지 추가

- build.gradle
- src/main/java/com/yello/server/domain/authorization/dto/response/OnBoardingFriend.java
- src/main/java/com/yello/server/domain/purchase/entity/Purchase.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
> YEL-178 [fix] 가입시 추천친구 학교네이밍 변경 & 가격 조정

- src/main/java/com/yello/server/domain/authorization/service/TokenJwtProvider.java
> token 시간 변경

- src/main/java/com/yello/server/domain/authorization/service/TokenJwtProvider.java
This reverts commit 649665627ef58de0a5ee5b5c7c155ab053710a05.
* resolves 
* 
*
> [hotfix] token 시간 변경

- src/docs/asciidoc/edit-user.adoc
- src/docs/asciidoc/find-friend-votes.adoc
- src/docs/asciidoc/find-notice.adoc
- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/purchase-info.adoc
- src/docs/asciidoc/search-department.adoc
- src/docs/asciidoc/search-high-class.adoc
- src/docs/asciidoc/search-high-name.adoc
- src/docs/asciidoc/search-school.adoc
- src/docs/asciidoc/user-data-get.adoc
- src/docs/asciidoc/user-data-post.adoc
- src/main/resources/static/docs/check-user-v2.html
- src/main/resources/static/docs/check-user.html
- src/main/resources/static/docs/check-vote-available.html
- src/main/resources/static/docs/edit-user.html
- src/main/resources/static/docs/find-friend-votes.html
- src/main/resources/static/docs/find-notice.html
- src/main/resources/static/docs/google.html
- src/main/resources/static/docs/purchase-info.html
- src/main/resources/static/docs/search-department.html
- src/main/resources/static/docs/search-high-class.html
- src/main/resources/static/docs/search-high-name.html
- src/main/resources/static/docs/search-school.html
- src/main/resources/static/docs/user-data-get.html
- src/main/resources/static/docs/user-data-post.html
* resolves 명세서 업데이트를 하였음
* 자잘한 오류 수정
* 
*
> YEL-182 [feat] 명세서 업데이트

- src/docs/asciidoc/purchase-info.adoc
- src/main/resources/static/docs/purchase-info.html
> YEL-163 [Docs] 명세서 수정

- src/docs/asciidoc/user-data-post.adoc
- src/main/java/com/yello/server/domain/user/controller/UserController.java
- src/main/java/com/yello/server/domain/user/dto/request/UserDeleteReasonRequest.java
- src/main/java/com/yello/server/domain/user/entity/UserData.java
- src/main/java/com/yello/server/domain/user/repository/UserDataJpaRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserDataRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserDataRepositoryImpl.java
- src/main/java/com/yello/server/domain/user/service/UserService.java
- src/main/resources/static/docs/check-vote-available.html
- src/main/resources/static/docs/find-notice.html
- src/main/resources/static/docs/google.html
- src/test/java/com/yello/server/domain/user/medium/UserControllerTest.java
* resolves YEL-184
* 유저 탈퇴 사유 저장
*
> YEL-184 [feat] 유저 탈퇴 사유 저장 v2

- src/main/java/com/yello/server/domain/notice/dto/NoticeDataResponse.java
- src/main/java/com/yello/server/domain/notice/entity/Notice.java
- src/main/java/com/yello/server/domain/notice/entity/NoticeType.java
- src/main/java/com/yello/server/domain/notice/entity/NoticeTypeConverter.java
- src/main/java/com/yello/server/domain/notice/service/NoticeService.java
- src/test/java/com/yello/server/domain/notice/FakeNoticeRepository.java
- src/test/java/com/yello/server/util/TestDataEntityUtil.java
- src/test/java/com/yello/server/util/TestDataRepositoryUtil.java
* resolves 
* 1. MySQL환경에서 Entity에 `type` 키워드를 쓰면 안됨. (단, dto는 상관없음)
* 2. type 대신 `tag`를 쓸 것
* 
*
> YEL-185 [feat] notice type 버그제거

- src/docs/asciidoc/find-notice.adoc
- src/main/java/com/yello/server/domain/notice/controller/NoticeController.java
- src/main/java/com/yello/server/domain/notice/repository/NoticeRepository.java
- src/main/java/com/yello/server/domain/notice/repository/NoticeRepositoryImpl.java
- src/main/java/com/yello/server/domain/notice/service/NoticeService.java
- src/test/java/com/yello/server/domain/notice/FakeNoticeRepository.java
- src/test/java/com/yello/server/domain/notice/medium/NoticeControllerTest.java
- src/test/java/com/yello/server/domain/notice/small/NoticeServiceTest.java
- src/test/java/com/yello/server/domain/user/medium/UserControllerTest.java
* resolves YEL-192
* tag에 대한 notice 조회
* notice tag 대문자로 전달해줘야 noticeType에서 enum 인식가능
*
> YEL-192 [fix] notice path variable에 tag 추가

- src/docs/asciidoc/find-notice.adoc
- src/main/java/com/yello/server/domain/notice/controller/NoticeController.java
- src/main/java/com/yello/server/domain/notice/entity/NoticeType.java
- src/main/java/com/yello/server/domain/notice/service/NoticeService.java
- src/main/resources/static/docs/find-notice.html
- src/main/resources/static/docs/index.html
- src/test/java/com/yello/server/domain/notice/medium/NoticeControllerTest.java
- src/test/java/com/yello/server/domain/notice/small/NoticeServiceTest.java
> YEL-207 [fix] notice tag 추가

- src/docs/asciidoc/create-event-history.adoc
- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/reward-event.adoc
- src/main/java/com/yello/server/domain/event/controller/EventController.java
- src/main/java/com/yello/server/domain/event/dto/request/EventJoinRequest.java
- src/main/java/com/yello/server/domain/event/dto/response/EventRewardResponse.java
- src/main/java/com/yello/server/domain/event/entity/EventInstance.java
- src/main/java/com/yello/server/domain/event/entity/EventInstanceReward.java
- src/main/java/com/yello/server/domain/event/exception/EventBadRequestException.java
- src/main/java/com/yello/server/domain/event/repository/EventHistoryJpaRepository.java
- src/main/java/com/yello/server/domain/event/repository/EventInstanceJpaRepository.java
- src/main/java/com/yello/server/domain/event/repository/EventInstanceRewardJpaRepository.java
- src/main/java/com/yello/server/domain/event/repository/EventJpaRepository.java
- src/main/java/com/yello/server/domain/event/repository/EventRepository.java
- src/main/java/com/yello/server/domain/event/repository/EventRepositoryImpl.java
- src/main/java/com/yello/server/domain/event/service/EventService.java
- src/main/java/com/yello/server/global/common/ErrorCode.java
- src/main/java/com/yello/server/global/common/SuccessCode.java
- src/main/java/com/yello/server/global/common/util/ConstantUtil.java
- src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
- src/main/resources/static/docs/create-event-history.html
- src/main/resources/static/docs/reward-event.html
- src/test/java/com/yello/server/domain/event/medium/EventControllerTest.java
> YEL-199 [feat] 이벤트 참여 API, 이벤트 보상 API

- src/main/java/com/yello/server/domain/authorization/configuration/SecurityConfiguration.java
> develop [develop] cors 임시 설정

- src/main/java/com/yello/server/domain/event/controller/EventController.java
- src/main/java/com/yello/server/domain/event/entity/EventType.java
- src/main/java/com/yello/server/global/exception/ControllerExceptionAdvice.java
- src/test/java/com/yello/server/domain/event/medium/EventControllerTest.java
> YEL-219 [fix] admob enum 수정, 로그 추가

- src/main/java/com/yello/server/domain/authorization/service/AuthService.java
- src/main/java/com/yello/server/domain/vote/service/VoteService.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationFcmService.java
- src/main/java/com/yello/server/infrastructure/firebase/service/NotificationService.java
- src/main/java/com/yello/server/infrastructure/scheduler/EventScheduler.java
- src/test/java/com/yello/server/infrastructure/firebase/NotificationFcmServiceTest.java
> YEL-214 [fix] 푸시알림 target, user 설정

- src/main/java/com/yello/server/domain/event/service/EventService.java
> develop [develop] (fix) 날짜별 기준 이벤트 참여이력 조회 로직 추가

- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
> [hotfix] slack message fix

- src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
- src/main/java/com/yello/server/domain/statistics/dto/RevenueVO.java
- src/main/java/com/yello/server/domain/statistics/dto/SignUpVO.java
- src/main/java/com/yello/server/domain/statistics/dto/VoteItem.java
- src/main/java/com/yello/server/domain/statistics/dto/VoteVO.java
- src/main/java/com/yello/server/domain/statistics/entity/StatisticsDaily.java
- src/main/java/com/yello/server/domain/statistics/service/StatisticsService.java
- src/main/java/com/yello/server/domain/statistics/task/StatisticsTask.java
- src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
- src/main/java/com/yello/server/domain/vote/repository/VoteRepository.java
- src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
- src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseRepository.java
- src/test/java/com/yello/server/domain/user/FakeUserRepository.java
- src/test/java/com/yello/server/domain/vote/FakeVoteRepository.java
> develop [develop] daily data report 추가

- src/main/java/com/yello/server/domain/purchase/repository/PurchaseJpaRepository.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepository.java
- src/main/java/com/yello/server/domain/purchase/repository/PurchaseRepositoryImpl.java
- src/main/java/com/yello/server/domain/statistics/dto/RevenueVO.java
- src/main/java/com/yello/server/domain/statistics/dto/SignUpVO.java
- src/main/java/com/yello/server/domain/statistics/dto/VoteItem.java
- src/main/java/com/yello/server/domain/statistics/dto/VoteVO.java
- src/main/java/com/yello/server/domain/statistics/entity/StatisticsDaily.java
- src/main/java/com/yello/server/domain/statistics/service/StatisticsService.java
- src/main/java/com/yello/server/domain/statistics/task/StatisticsTask.java
- src/main/java/com/yello/server/domain/user/repository/UserJpaRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepository.java
- src/main/java/com/yello/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/yello/server/domain/vote/repository/VoteJpaRepository.java
- src/main/java/com/yello/server/domain/vote/repository/VoteRepository.java
- src/main/java/com/yello/server/domain/vote/repository/VoteRepositoryImpl.java
- src/main/java/com/yello/server/infrastructure/slack/factory/SlackWebhookMessageFactory.java
- src/test/java/com/yello/server/domain/purchase/FakePurchaseRepository.java
- src/test/java/com/yello/server/domain/user/FakeUserRepository.java
- src/test/java/com/yello/server/domain/vote/FakeVoteRepository.java
> [deploy] daily data report 추가

- src/main/java/com/yello/server/domain/statistics/task/StatisticsTask.java
> develop [develop] 학교대항전 task 삭제

- .gitignore
- appspec.yml
- scripts/deploy.sh
> develop [develop] fix: ubuntu migration

- appspec.yml
> develop [develop] fix: file dup

- scripts/deploy.sh
> develop [develop] 상대경로 변경

- appspec.yml
> develop [develop] fix: rel -> abs

- docker/docker-compose.blue.yml
- docker/docker-compose.green.yml
> develop [develop] fix: redis 삭제

- src/main/resources/static/docs/index.html
- src/main/resources/static/docs/reward-admob.html
> develop [develop] update domain
